talk/urls.py
from django.urls import path , include
from . import views


app_name = 'talk'

urlpatterns = [
    path('',views.home , name='home'),
    path('d/',views.d , name='d'),
    path('<slug:post>/', views.post_single, name='post_single'),
    path('category/<category>/', views.CatListView.as_view(), name='category'),
    path('ques',views.question , name='question'),
    path('album', views.album, name = 'album-list'),
    path('album/like',views.like , name='like-album'),
    path('contact',views.contact , name='contact'),
    path('fav/<int:id>/',views.favourite_add , name='favourite_add'),
    path('profile/favourites',views.favourite_list ,name='favourite_list'),

]

talk_d/urls.py
from django.contrib import admin
from django.urls import path , include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('talk.urls')),
    # path('albums/',include('talk.urls' , namespace='talk'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

talk/models.py
from django.db import models
from datetime import datetime
from django.db.models.expressions import Value
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel ,TreeForeignKey

# Create your models here.



def user_directory_path(instance, filename):
    return 'posts/%Y/%m/%d/'.format(instance.id, filename)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=250)
    excerpt = models.TextField(null=True)
    image = models.ImageField(
        upload_to=user_directory_path, default='posts/default.jpg')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='draft')
    favourites = models.ManyToManyField(User,related_name='favourite',default=None, blank=True)
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager

    def get_absolute_url(self):
        return reverse('talk:post_single', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    parent = TreeForeignKey('self',on_delete=models.CASCADE,null = True , blank=True,related_name='children')
    name = models.CharField(max_length=50)
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return f'Comment by {self.name}'

# like button code 

class Album(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    liked = models.ManyToManyField(User,default=None,blank=True,related_name='liked')
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='author')
    def __str__(self):
        return str(self.title)
    @property
    def num_likes(self):
        return self.liked.all().count()

LIKE_CHOICES = {
        ('like' , 'like'),
        ('unlike' , 'unlike'),
    }

class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Album,on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES,default='like',max_length=10)
    def __str__(self):
        return str(self.post)

# contact us code 

class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    message = models.CharField(max_length=500, default="")


    def __str__(self):
        return self.first_name

talk/forms.py
from django import forms
from .models import Comment
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
        parent = TreeNodeChoiceField(queryset=Comment.objects.all())
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)


            self.fields['parent'].widget.attrs.update(
                {'class': 'd-none'})
            self.fields['parent'].label = ''
            self.fields['parent'].required = False
        
        class Meta:
            model = Comment
            fields = ('name', 'parent', 'content')
            widgets = {
                'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
                'content': forms.Textarea(attrs={'class': 'form-control'}),
            }
        def save(self, *args, **kwargs):
            Comment.objects.rebuild()
            return super(NewCommentForm, self).save(*args, **kwargs)

class Question(forms.Form):
    Name = forms.CharField()
    category = forms.ChoiceField(choices=[('question','Question') ,('answer' , 'Answer')])
    question = forms.CharField(widget=forms.Textarea) 

talk/views.py
from django.db.models.expressions import Value
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect , redirect
from .models import Post, Comment, Category , Like ,Album ,Contact
from .forms import NewCommentForm , Question
from django.core.mail import message, send_mail, BadHeaderError
from django.http import HttpResponse
from django.views.generic import ListView
from django.core.paginator import Paginator ,EmptyPage,PageNotAnInteger
from django.contrib.auth import login


def d(request):
    return render(request,'d.html')

def home(request):

    all_posts = Post.newmanager.all()
    
    return render(request, 'h.html', {'posts': all_posts})


def post_single(request, post):
    if(request.method == 'POST'):
        form = Question(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            body ={
                'Name': form.changed_data['Name'],
                'Email': form.changed_data['Email'],
                'category': form.changed_data['category'],
                'question': form.changed_data['question'],
            }
            message = '\n'.join(body.values())
            try:
                send_mail(subject, message, 'admin@example.com', ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect("/")

    

    post = get_object_or_404(Post, slug=post, status='published')

    fav = bool
    if post.favourites.filter(id=request.user.id).exists():
        fav = True


    allcomments = post.comments.filter(status=True)
    page = request.GET.get('page', 1)

    paginator = Paginator(allcomments, 10)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/' + post.slug)
    else:
        comment_form = NewCommentForm()
    form = Question()
    return render(request, 'd.html', {'post': post, 'comments':  user_comment, 'comments': comments, 'comment_form': comment_form,'form':form,'fav':fav })


class CatListView(ListView):
    template_name = 'category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs['category']).filter(status='published')
        }
        return content


def category_list(request):
    category_list = Category.objects.exclude(name='default')
    context = {
        "category_list": category_list,
    }
    return context

def question(request):
    if(request.method == 'POST'):
        form = Question(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            body ={
                'Name': form.changed_data['Name'],
                'category': form.changed_data['category'],
                'question': form.changed_data['question'],
            }
            message = '\n'.join(body.values())
            try:
                send_mail(subject, message, 'admin@example.com', ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect("/")

    form = Question()
    return render (request , 'h.html' , {'form':form})

# like unlike code 

def album(request):
    qs=Album.objects.all()
    user = request.user
    context = {
        'qs':qs,
        'user':user
    }
    return render(request,'main.html',context)

def like(request):
    user = request.user
    if request.method == 'POST':
        album_id = request.POST.get('album_id')
        album_obj = Album.objects.get(id=album_id)
        if user in album_obj.liked.all():
            album_obj.liked.remove(user)
        else :
            album_obj.liked.add(user)
        like , created = Like.objects.get_or_create(user=user,post_id = album_id)

        if not created:
            if like.value == 'like':
                like.value = 'unlike'
            else:
                like.value = 'like'
        like.save()
    return redirect('talk:album-list')

#contact us

def contact(request):
    if request.method=="POST":
        first_name=request.POST.get('first_name', '')
        last_name=request.POST.get('last_name', '')
        email=request.POST.get('email', '')
        phone=request.POST.get('contact_no', '')
        message=request.POST.get('message', '')
        print(first_name,last_name,email,phone,message)
        contact = Contact(first_name=first_name,last_name=last_name, email=email, phone=phone, message=message)
        contact.save()
    return render(request,"contact.html")


#favourites/Bookmark

def favourite_add(request ,id):
    post = get_object_or_404(Post,id=id)
    if post.favourites.filter(id=request.user.id).exists():
        post.favourites.remove(request.user)
    else :
        post.favourites.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def favourite_list(request):
    new = Post.newmanager.filter(favourites = request.user)
    return render(request,'favourites.html',{'new':new})

talk/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="Description" content="Enter your description here" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
  <link rel="stylesheet" href="assets/css/style.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>{% block title %} Welcome to blog {% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">D-talk</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Create Post
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for category in category_list %}
            <a class="dropdown-item" href="/category/{{ category.name}}">
              {{ category.name|title }}
            </a>
            {% endfor %}
          </div>
        </li>
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
</body>

</html>

talk/templates/category.html
    {% extends "base.html" %}

    {% block title %}
   Catlist
    {% endblock %}

    {% block content %}
    
       <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
        <div class="col-12 pb-5"><h1> List of {{catlist.cat}} posts</h1></div>
        {% for post in catlist.posts %}
            <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                <div class="card-body">
                  <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                  <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
              </a>
            </div>
        {% endfor %}
          </div>
        </div>
      </div>

    {% endblock %}

talk/templates/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <title>Contact Us</title>
</head>

<body>
    <div class="container">
        <h3>Contact Us</h3>
        <form action="{% url 'talk:contact' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">First Name</label>
                <input type="text" class="form-control" id="name" name="first_name" placeholder="Enter Your Name">
            </div>
            <div class="form-group">
                <label for="name">Last Name</label>
                <input type="text" class="form-control" id="name" name="last_name" placeholder="Enter Your Name">
            </div>
            <div class="form-group">
                <label for="name">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter Your Email">
            </div>
            <div class="form-group">
                <label for="name">Contact No</label>
                <input type="tel" class="form-control" id="phone" name="phone" placeholder="Enter Your Phone Number">
            </div>
            <div class="form-group">
                <div class="form-group">
                    <label for="desc">Message</label>
                    <textarea class="form-control" id="desc" name="message" rows="3"></textarea>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
        </form>

                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
                <script
                    src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
</body>

</html>

talk/templates/demo.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <title>demo</title>
</head>

<body>
    <article
        class="question question-type-poll question_author_yes post-2492 type-question status-publish hentry question-category-language question_tags-germany"
        id="post-2492" itemscope="" itemtype="https://schema.org/Question">
        <h2> <a itemprop="url"
                href="https://2code.info/demo/themes/ask-me/question/do-i-need-to-have-a-undergrad-percentage-of-70-to-do-my-masters-in-germany/"
                title="Do I need to have a undergrad percentage of 70% to do my masters in Germany?" rel="bookmark">
                <span itemprop="name">Do I need to have a undergrad percentage of 70% to do my masters in
                    Germany?</span> </a>
        </h2> <a class="question-report report_q" href="#">Report</a>
        <div class="question-type-main"><i class="icon-signal"></i>Poll</div>
        <div class="question-author" itemprop="author" itemscope="" itemtype="https://schema.org/Person"> <span
                itemprop="name" class="hide">Ahmed Hassan</span> <a
                href="https://2code.info/demo/themes/ask-me/author/ask-me/" original-title="Ahmed Hassan"
                class="question-author-img tooltip-n"> <span></span> <img itemprop="image"
                    class="avatar avatar-65 photo" alt="Ahmed Hassan" width="65" height="65"
                    src="https://2code.info/demo/themes/ask-me/wp-content/uploads/2017/07/team-7-65x65.jpg"> </a></div>
        <div class="question-inner">
            <div class="clearfix"></div>
            <div class="question-desc">
                <div itemprop="text">Participate in the referendum, Please.</div>
                <div class="explain-reported">
                    <h3>Please briefly explain why you feel this question should be reported .</h3><textarea
                        name="explain-reported"></textarea>
                    <div class="clearfix"></div>
                    <div class="loader_3"></div>
                    <div class="color button small report">Report</div>
                    <div class="color button small dark_button cancel">Cancel</div>
                </div>
                <div class="no_vote_more"></div>
            </div>
            <div class="question-details"> <span class="question-favorite"><i class="icon-star"></i>15</span></div>
            <span class="question-category"><i class="fa fa-folder-o"></i><a
                    href="https://2code.info/demo/themes/ask-me/question-category/language/"
                    rel="tag">Language</a></span>
            <span class="question-author-meta"> </span> <span class="question-date" itemprop="dateCreated"
                datetime="November 19, 2017"><i class="fa fa-calendar"></i>3 years</span> <span
                class="question-comment"><a
                    href="https://2code.info/demo/themes/ask-me/question/do-i-need-to-have-a-undergrad-percentage-of-70-to-do-my-masters-in-germany/#respond"><i
                        class="fa fa-comments-o"></i><span itemprop="answerCount">0</span> </a></span> <span
                class="question-view"><i class="icon-eye-open"></i>10967 views</span> <span class="badge-span"
                style="background-color: #81d742">Explainer</span>
            <div class="clearfix"></div>
        </div>
    </article>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
</body>

</html>

talk/templates/favourites.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>bookmark</title>
</head>
<body>
    <div>
        <div class="row">
            {% for  post in new %}
            <div class="col-md-4">
                <a href="{{post.get_absolute_url}}" class="text-dark">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{{post.image.url}}" alt="{{post.title}}">
                        <div class="card-body">
                            <h2 style="font-size: 18px; font-weight: bold;">{{post.title|truncatechars:50}}</h2>
                            <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                            <div class='d-flex justify-content-between align-items-center'>
                                <small class="text-muted">9 mins</small>
                                <div id='favourite-secton'>
                                    <a href="{% url 'talk:favourite_add' post.id %}" class='btn btn-outline-dark'>
                                        Remove
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
</body>
</html>

talk/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>album</title>
</head>
<body>
    {% for obj in qs %}
        <h1>{{ obj.title }}</h1>
        <p>{{obj.body}}</p>
        <form action="{% url 'talk:like-album' %}" method="POST" class='btn btn-light'>
            {% csrf_token %}
            <input type="hidden" name="album_id" value="{{ obj.id }}">
            {% if user not in obj.liked.all %}
                <button class="btn btn-success" type="submit">Like</button>
            {% else %}
                <button class="btn btn-danger" type="submit">Unlike</button>
            {% endif %}
            <strong>{{ obj.liked.all.count }} likes</strong>
        </form>
    {% endfor %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
</body>
</html>

talk/templates/ques.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style="margin:80px">
        <h1>Contact</h1>
        <h4>Contact us directly if you have any questions</h4>
        <p>
            Please write your name, email address and a message below if you have any questions.
            One of our staff members will be happy to contact you directly and answer your questions as soon as
            possible.
        </p>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

talk/templates/single.html
{% extends "base.html" %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}

<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }
</style>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
      <h1 class="display-4">D-talk</h1>
      <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>
<div class='d-fl'></div>
<div class="container">
  <div class="row justify-content-md-center pt-5">

    <div class="col-md-7">
      <h1>{{post.title}}</h1>
    </div>
    <div class="col-md-9"><img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}"></div>
    <div class="col-md-7">
      <p>{{post.content|safe}}</p>
    </div>
    <div class="col-md-7">

      {% with allcomments.count as total_comments %}
      <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h2>
      {% endwith %}

      {% load mptt_tags %}

      <div>
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h1 class="display-4">D-talk</h1>
            <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
          </div>
        </div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="my-2 p-2" style="border: 1px solid grey">
          <div class="d-flex justify-content-between">By {{ node.name }}<div></div>{{ node.publish }}</div>
          <div>{{ node.content }}</div>
          <hr />
          {% if node.level < 3 %} <button class="button" onclick="myFunction({{node.id}})">Reply</button>
            {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>

      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>

      <div id="myDIV" style="display:block;">
        <form id="myForm" method="post">
          <h2>Create new comment</h2>
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
        </form>
      </div>

    </div>
  </div>
</div>
<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                <label for="id_name">Name:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_email">Email:</label> \
                <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email"> \
                <label for="id_content">Content:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                {% csrf_token %} \
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
              </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>

{% endblock %}